// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Home documents
 */
interface BannerDaHomeDocumentData {
  /**
   * Titulo field in *Home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_da_home.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.TitleField;

  /**
   * Descrição field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_da_home.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao: prismic.KeyTextField;

  /**
   * Banner da home field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_da_home.banner_da_home
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner_da_home: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `banner_da_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BannerDaHomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BannerDaHomeDocumentData>,
    "banner_da_home",
    Lang
  >;

/**
 * Item in *Como Funciona → Cards*
 */
export interface ComoFuncionaDocumentDataCardsItem {
  /**
   * Ícone field in *Como Funciona → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: como_funciona.cards[].icone
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone: prismic.ImageField<never>;

  /**
   * Título field in *Como Funciona → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_funciona.cards[].titulo1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo1: prismic.KeyTextField;

  /**
   * Descrição field in *Como Funciona → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_funciona.cards[].descricao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao: prismic.KeyTextField;
}

/**
 * Content for Como Funciona documents
 */
interface ComoFuncionaDocumentData {
  /**
   * Título field in *Como Funciona*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_funciona.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Subtítulo field in *Como Funciona*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: como_funciona.subtitulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Cards field in *Como Funciona*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: como_funciona.cards[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<ComoFuncionaDocumentDataCardsItem>>;
}

/**
 * Como Funciona document from Prismic
 *
 * - **API ID**: `como_funciona`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ComoFuncionaDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ComoFuncionaDocumentData>,
    "como_funciona",
    Lang
  >;

/**
 * Content for Entrada do Site documents
 */
interface EntradaDoSiteDocumentData {
  /**
   * Título field in *Entrada do Site*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: entrada_do_site.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Subtítulo field in *Entrada do Site*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: entrada_do_site.subtitulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulo: prismic.KeyTextField;

  /**
   * Link do Botão field in *Entrada do Site*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: entrada_do_site.link_do_botao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_do_botao: prismic.KeyTextField;

  /**
   * Banner field in *Entrada do Site*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: entrada_do_site.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>;

  /**
   * Título do card field in *Entrada do Site*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: entrada_do_site.titulo_do_card
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo_do_card: prismic.KeyTextField;

  /**
   * Descrição do card field in *Entrada do Site*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: entrada_do_site.descricao_do_card
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao_do_card: prismic.KeyTextField;
}

/**
 * Entrada do Site document from Prismic
 *
 * - **API ID**: `entrada_do_site`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EntradaDoSiteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<EntradaDoSiteDocumentData>,
    "entrada_do_site",
    Lang
  >;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Titulo field in *Home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.TitleField;

  /**
   * Descrição field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao: prismic.KeyTextField;

  /**
   * imagem field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.imagem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

interface OrentacoesAoPacienteDocumentData {}

/**
 * Orientações ao Pacientee document from Prismic
 *
 * - **API ID**: `orentacoes_ao_paciente`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OrentacoesAoPacienteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<OrentacoesAoPacienteDocumentData>,
    "orentacoes_ao_paciente",
    Lang
  >;

interface OrientacesAoPacienteDocumentData {}

/**
 * Orientaces ao Paciente document from Prismic
 *
 * - **API ID**: `orientaces_ao_paciente`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OrientacesAoPacienteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<OrientacesAoPacienteDocumentData>,
    "orientaces_ao_paciente",
    Lang
  >;

/**
 * Content for Orientações ao Paciente documents
 */
interface OrientacoesAoPacienteDocumentData {
  /**
   * Orientações ao Paciente field in *Orientações ao Paciente*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: orientacoes_ao_paciente.orientacoes_ao_paciente
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  orientacoes_ao_paciente: prismic.TitleField;

  /**
   * Orientações ao Paciente field in *Orientações ao Paciente*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: orientacoes_ao_paciente.orientacoes_ao_paciente1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  orientacoes_ao_paciente1: prismic.ImageField<never>;

  /**
   * Orientações ao Paciente field in *Orientações ao Paciente*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: orientacoes_ao_paciente.orientacoes_ao_paciente2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  orientacoes_ao_paciente2: prismic.RichTextField;
}

/**
 * Orientações ao Paciente document from Prismic
 *
 * - **API ID**: `orientacoes_ao_paciente`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OrientacoesAoPacienteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<OrientacoesAoPacienteDocumentData>,
    "orientacoes_ao_paciente",
    Lang
  >;

/**
 * Content for Orientações Paciente documents
 */
interface OrientacoesPacienteDocumentData {
  /**
   * Banner field in *Orientações Paciente*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: orientacoes_paciente.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>;

  /**
   * Título field in *Orientações Paciente*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: orientacoes_paciente.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Descrição field in *Orientações Paciente*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: orientacoes_paciente.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao: prismic.KeyTextField;

  /**
   * Conteúdo field in *Orientações Paciente*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: orientacoes_paciente.conteudo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;
}

/**
 * Orientações Paciente document from Prismic
 *
 * - **API ID**: `orientacoes_paciente`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type OrientacoesPacienteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<OrientacoesPacienteDocumentData>,
    "orientacoes_paciente",
    Lang
  >;

/**
 * Item in *Perguntas Frequentes → Perguntas Frequentes*
 */
export interface PerguntaFrequenteDocumentDataPerguntasFrequentesItem {
  /**
   * Pergunta field in *Perguntas Frequentes → Perguntas Frequentes*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: pergunta_frequente.perguntas_frequentes[].pergunta
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pergunta: prismic.TitleField;

  /**
   * Resposta field in *Perguntas Frequentes → Perguntas Frequentes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pergunta_frequente.perguntas_frequentes[].resposta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resposta: prismic.KeyTextField;

  /**
   * Mostrar na página principal? field in *Perguntas Frequentes → Perguntas Frequentes*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: pergunta_frequente.perguntas_frequentes[].mostrar_na_pagina_principal_
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  mostrar_na_pagina_principal_: prismic.BooleanField;
}

/**
 * Content for Perguntas Frequentes documents
 */
interface PerguntaFrequenteDocumentData {
  /**
   * Descrição field in *Perguntas Frequentes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pergunta_frequente.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao: prismic.KeyTextField;

  /**
   * Perguntas Frequentes field in *Perguntas Frequentes*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pergunta_frequente.perguntas_frequentes[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  perguntas_frequentes: prismic.GroupField<
    Simplify<PerguntaFrequenteDocumentDataPerguntasFrequentesItem>
  >;
}

/**
 * Perguntas Frequentes document from Prismic
 *
 * - **API ID**: `pergunta_frequente`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PerguntaFrequenteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PerguntaFrequenteDocumentData>,
    "pergunta_frequente",
    Lang
  >;

/**
 * Content for Politica de privacidade documents
 */
interface PoliticaDePrivacidadeDocumentData {
  /**
   * Politica de privacidade field in *Politica de privacidade*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: politica_de_privacidade.politica_de_privacidade
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  politica_de_privacidade: prismic.RichTextField;
}

/**
 * Politica de privacidade document from Prismic
 *
 * - **API ID**: `politica_de_privacidade`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PoliticaDePrivacidadeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PoliticaDePrivacidadeDocumentData>,
    "politica_de_privacidade",
    Lang
  >;

/**
 * Content for Post documents
 */
interface PostDocumentData {
  /**
   * Tipo de Post field in *Post*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Post
   * - **API ID Path**: post.tipo_de_post
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tipo_de_post: prismic.SelectField<"Post" | "Seus Direitos", "filled">;

  /**
   * Título field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Imagem field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.imagem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;

  /**
   * Banner field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>;

  /**
   * Conteudo field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.conteudo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Anúncio field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.anuncio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  anuncio: prismic.ImageField<never>;

  /**
   * Link do anuncio field in *Post*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: post.link_do_anuncio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_do_anuncio: prismic.LinkField;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<PostDocumentData>, "post", Lang>;

/**
 * Content for Redes Sociais documents
 */
interface RedesSociaisDocumentData {
  /**
   * Facebook field in *Redes Sociais*
   *
   * - **Field Type**: Link
   * - **Placeholder**: link do facebook
   * - **API ID Path**: redes_sociais.facebook
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook: prismic.LinkField;

  /**
   * Instagram field in *Redes Sociais*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: redes_sociais.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkToMediaField;

  /**
   * Whatsapp field in *Redes Sociais*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: redes_sociais.whatsapp
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  whatsapp: prismic.LinkField;
}

/**
 * Redes Sociais document from Prismic
 *
 * - **API ID**: `redes_sociais`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RedesSociaisDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RedesSociaisDocumentData>,
    "redes_sociais",
    Lang
  >;

/**
 * Item in *Sobre nós → Icones*
 */
export interface SobreNosDocumentDataIconesItem {
  /**
   * Icone field in *Sobre nós → Icones*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.icones[].icone
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone: prismic.ImageField<never>;

  /**
   * Texto field in *Sobre nós → Icones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.icones[].texto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texto: prismic.KeyTextField;
}

/**
 * Content for Sobre nós documents
 */
interface SobreNosDocumentData {
  /**
   * Primeira imagem field in *Sobre nós*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.primeira_imagem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  primeira_imagem: prismic.ImageField<never>;

  /**
   * Titulo field in *Sobre nós*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo: prismic.TitleField;

  /**
   * Descrição field in *Sobre nós*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao: prismic.RichTextField;

  /**
   * Icones field in *Sobre nós*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.icones[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  icones: prismic.GroupField<Simplify<SobreNosDocumentDataIconesItem>>;

  /**
   * Banner field in *Sobre nós*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>;

  /**
   * Titulo field in *Sobre nós*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.titulo1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulo1: prismic.TitleField;

  /**
   * Descrição field in *Sobre nós*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sobre_nos.descricao1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao1: prismic.RichTextField;
}

/**
 * Sobre nós document from Prismic
 *
 * - **API ID**: `sobre_nos`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SobreNosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SobreNosDocumentData>,
    "sobre_nos",
    Lang
  >;

/**
 * Content for teste documents
 */
interface TesteDocumentData {
  /**
   * tes field in *teste*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: teste.tes
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tes: prismic.KeyTextField;
}

/**
 * teste document from Prismic
 *
 * - **API ID**: `teste`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TesteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<TesteDocumentData>, "teste", Lang>;

/**
 * Content for Welcome documents
 */
interface WelcomeDocumentData {
  /**
   * message field in *Welcome*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message: prismic.KeyTextField;

  /**
   * data field in *Welcome*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.data
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  data: prismic.KeyTextField;

  /**
   * yrs field in *Welcome*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.yrs
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  yrs: prismic.KeyTextField;

  /**
   * te field in *Welcome*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.tes
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tes: prismic.KeyTextField;

  /**
   * werwer field in *Welcome*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.werwer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  werwer: prismic.KeyTextField;
}

/**
 * Welcome document from Prismic
 *
 * - **API ID**: `welcome`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WelcomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<WelcomeDocumentData>,
    "welcome",
    Lang
  >;

export type AllDocumentTypes =
  | BannerDaHomeDocument
  | ComoFuncionaDocument
  | EntradaDoSiteDocument
  | HomeDocument
  | OrentacoesAoPacienteDocument
  | OrientacesAoPacienteDocument
  | OrientacoesAoPacienteDocument
  | OrientacoesPacienteDocument
  | PerguntaFrequenteDocument
  | PoliticaDePrivacidadeDocument
  | PostDocument
  | RedesSociaisDocument
  | SobreNosDocument
  | TesteDocument
  | WelcomeDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BannerDaHomeDocument,
      BannerDaHomeDocumentData,
      ComoFuncionaDocument,
      ComoFuncionaDocumentData,
      ComoFuncionaDocumentDataCardsItem,
      EntradaDoSiteDocument,
      EntradaDoSiteDocumentData,
      HomeDocument,
      HomeDocumentData,
      OrentacoesAoPacienteDocument,
      OrentacoesAoPacienteDocumentData,
      OrientacesAoPacienteDocument,
      OrientacesAoPacienteDocumentData,
      OrientacoesAoPacienteDocument,
      OrientacoesAoPacienteDocumentData,
      OrientacoesPacienteDocument,
      OrientacoesPacienteDocumentData,
      PerguntaFrequenteDocument,
      PerguntaFrequenteDocumentData,
      PerguntaFrequenteDocumentDataPerguntasFrequentesItem,
      PoliticaDePrivacidadeDocument,
      PoliticaDePrivacidadeDocumentData,
      PostDocument,
      PostDocumentData,
      RedesSociaisDocument,
      RedesSociaisDocumentData,
      SobreNosDocument,
      SobreNosDocumentData,
      SobreNosDocumentDataIconesItem,
      TesteDocument,
      TesteDocumentData,
      WelcomeDocument,
      WelcomeDocumentData,
      AllDocumentTypes,
    };
  }
}
