// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Dados e Redes Sociais documents
 */
interface DadosERedesSociaisDocumentData {
  /**
   * Whatsapp field in *Dados e Redes Sociais*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ex: 999999999999
   * - **API ID Path**: dados_e_redes_sociais.whatsapp
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  whatsapp: prismic.KeyTextField;

  /**
   * Instagram field in *Dados e Redes Sociais*
   *
   * - **Field Type**: Text
   * - **Placeholder**: @seuinstagram
   * - **API ID Path**: dados_e_redes_sociais.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagram: prismic.KeyTextField;

  /**
   * Linkedin field in *Dados e Redes Sociais*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /seulinkedin
   * - **API ID Path**: dados_e_redes_sociais.linkedin
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  linkedin: prismic.KeyTextField;

  /**
   * Facebook field in *Dados e Redes Sociais*
   *
   * - **Field Type**: Text
   * - **Placeholder**: @seufacebook
   * - **API ID Path**: dados_e_redes_sociais.facebook
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  facebook: prismic.KeyTextField;

  /**
   * Email field in *Dados e Redes Sociais*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dados_e_redes_sociais.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Endereço field in *Dados e Redes Sociais*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dados_e_redes_sociais.endereco
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  endereco: prismic.KeyTextField;

  /**
   * Telefone field in *Dados e Redes Sociais*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: (99) 99999-9999
   * - **API ID Path**: dados_e_redes_sociais.telefone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  telefone: prismic.KeyTextField;
}

/**
 * Dados e Redes Sociais document from Prismic
 *
 * - **API ID**: `dados_e_redes_sociais`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DadosERedesSociaisDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<DadosERedesSociaisDocumentData>,
    "dados_e_redes_sociais",
    Lang
  >;

/**
 * Content for Post documents
 */
interface PostDocumentData {
  /**
   * Título field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Capa field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.capa
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  capa: prismic.ImageField<never>;

  /**
   * Autor field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.autor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  autor: prismic.KeyTextField;

  /**
   * Conteúdo field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.conteudo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  conteudo: prismic.RichTextField;

  /**
   * Resumo field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.resumo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  resumo: prismic.KeyTextField;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;

/**
 * Content for Serviço documents
 */
interface ServicoDocumentData {
  /**
   * Título field in *Serviço*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: servico.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Descrição field in *Serviço*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: servico.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descricao: prismic.RichTextField;
}

/**
 * Serviço document from Prismic
 *
 * - **API ID**: `servico`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServicoDocumentData>,
    "servico",
    Lang
  >;

export type AllDocumentTypes =
  | DadosERedesSociaisDocument
  | PostDocument
  | ServicoDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DadosERedesSociaisDocument,
      DadosERedesSociaisDocumentData,
      PostDocument,
      PostDocumentData,
      ServicoDocument,
      ServicoDocumentData,
      AllDocumentTypes,
    };
  }
}
