import type { NextPage, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import { client } from '../services/prismicClient'
import useSWR from 'swr'

// type inferedTypes = InferGetStaticPropsType<typeof getStaticProps>

const Home: NextPage = () => {
  const { data: bannersHome } = useSWR('banners_da_home', () =>
    client.getSingle('banners_da_home')
  )

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center flex-col gap-5 pt-4">
        <h1 className="text-white">Front-end Next 12 Template</h1>
      </main>
    </div>
  )
}

export default Home
