import type { NextPage, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import ButtonSolid from '../components/Buttons/ButtonSolid'
import ButtonOutline from '../components/Buttons/ButtonOutline'

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Next Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center flex-col gap-5 pt-4 h-screen">
        <h1>Front-end Next 12 Template</h1>
        <ButtonSolid>Button Solid</ButtonSolid>
        <ButtonOutline>Button Outline</ButtonOutline>
      </main>
    </div>
  )
}
export default Home
