import type { NextPage } from 'next'
import Head from 'next/head'
import { client } from '../services/prismicClient'

const Home: NextPage = ({ contatos }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center justify-center flex-col gap-5 pt-4">
        <h1 className="text-white">Front-end Next 12 Template</h1>
        <p>{contatos?.data.email}</p>
        <p>{contatos?.data.facebook}</p>
        <p>{contatos?.data.instagram}</p>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const contatos = await client.getSingle('contatos')

  return {
    props: {
      contatos,
    },
    revalidate: 60, // In seconds
  }
}

export default Home
